# Generated by Django 5.0.6 on 2024-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_cruds_category_cruds_ads_cruds_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruds',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
